import 'package:hive_flutter/hive_flutter.dart';
import '../models/game_state.dart';
import '../models/character.dart';
import '../models/item.dart';

/// Handles all save/load operations using Hive (offline-first).
class SaveService {
  static const String _saveBoxName = 'cursed_realm_save';
  static const String _saveKey = 'game_state';

  static Box? _box;

  /// Initialize Hive and open the save box.
  static Future<void> init() async {
    await Hive.initFlutter();
    _registerAdapters();
    _box = await Hive.openBox(_saveBoxName);
  }

  static void _registerAdapters() {
    // Register all Hive adapters generated by hive_generator.
    // These are generated when you run: flutter pub run build_runner build
    // For now they are listed here as a reference. Uncomment after generation:
    //
    // Hive.registerAdapter(CharacterClassAdapter());
    // Hive.registerAdapter(CharacterStatsAdapter());
    // Hive.registerAdapter(StatGrowthAdapter());
    // Hive.registerAdapter(CharacterAdapter());
    // Hive.registerAdapter(EquipmentSlotsAdapter());
    // Hive.registerAdapter(ItemTypeAdapter());
    // Hive.registerAdapter(ItemRarityAdapter());
    // Hive.registerAdapter(StatBonusAdapter());
    // Hive.registerAdapter(ItemAdapter());
    // Hive.registerAdapter(InventoryAdapter());
    // Hive.registerAdapter(SkillTypeAdapter());
    // Hive.registerAdapter(SkillTargetTypeAdapter());
    // Hive.registerAdapter(DamageTypeAdapter());
    // Hive.registerAdapter(SkillEffectAdapter());
    // Hive.registerAdapter(StatusEffectTypeAdapter());
    // Hive.registerAdapter(SkillAdapter());
    // Hive.registerAdapter(EnemyTierAdapter());
    // Hive.registerAdapter(EnemyAIPatternAdapter());
    // Hive.registerAdapter(LootEntryAdapter());
    // Hive.registerAdapter(EnemyStatsAdapter());
    // Hive.registerAdapter(EnemyDefinitionAdapter());
    // Hive.registerAdapter(GamePhaseAdapter());
    // Hive.registerAdapter(DungeonProgressAdapter());
    // Hive.registerAdapter(GameStateAdapter());
  }

  /// Save the current game state.
  static Future<void> saveGame(GameState state) async {
    final box = _box;
    if (box == null) return;
    await box.put(_saveKey, state);
  }

  /// Load the saved game state. Returns null if no save exists.
  static GameState? loadGame() {
    final box = _box;
    if (box == null) return null;
    return box.get(_saveKey) as GameState?;
  }

  /// Check if a save file exists.
  static bool hasSave() {
    return _box?.containsKey(_saveKey) ?? false;
  }

  /// Delete save data (new game / reset).
  static Future<void> deleteSave() async {
    await _box?.delete(_saveKey);
  }

  /// Close the box when done.
  static Future<void> close() async {
    await _box?.close();
  }
}
